#!/bin/bash
# Autor:                Jensy Gregorio Gomez
# Bio:                  Tecnico em Informatica e Eletronica
# YouTube:              youtube.com/Sys-tech
# Instagram:            https://www.instagram.com/systech5/?hl=pt-br
# Github:               https://github.com/systech-brz

# Data de criação:      01/01/2022
# Data de atualização:  01/01/2022
# Versão:               0.01

# Testado e homologado para a versão do Ubuntu Server 20.04.x LTS x64
# Testado e homologado para a versão do Bind9 DNS Server v9.16.x
#
# Desabilitar o suporte ao Resolvconf
RESOLVCONF=no
#
# Opções de inicialização do serviço do Bind9 DNS Server
# opções do options: -u (user), -4 (ipv4)
OPTIONS="-u bind -4"